config/routes.rb
Sidrat::Application.routes.draw do

  namespace :backend do
    resources :doctors, :except => [:new, :create, :destroy]
    resources :companions, :except => [:destroy]
    resources :series, :except => [:new, :create, :destroy] do
      resources :entries, :except => [:index, :destroy]
    end
  end
  
  match '/search/companion' => 'searches#companion'
  match '/search/contributor' => 'searches#contributor'
  match '/search/publisher' => 'searches#publisher'
  
  match '/backend/index' => 'backend#index'
  match '/backend' => 'backend#index'
  
  
  match '/doctors' => 'doctors#index'
  

  root :to => 'sidrat#index'

end

app/models/companion.rb
class Companion < ActiveRecord::Base
  has_and_belongs_to_many :doctors, :readonly => true
  has_and_belongs_to_many :entries
  
  attr_accessor :uploaded_image
  
  validates :name, 
    :uniqueness => { 
      :message => 'That person already appears to be in the database'
    }
  validates_with ImageValidator, :fields => [:uploaded_image]
  
  before_save do
    unless uploaded_image.nil?
      logger.debug 'Generating full size and icon resources'
      resource = Image.new(uploaded_image)
      resource.prefix = "companion-#{id}"
      
      resource.convert
      resource.copy("#{Rails.root}/app/assets/images/companions")
      self.icon = "companions/#{resource.icon}"
      self.image = "companions/#{resource.full}"
      
      resource.destroy
    end
  end

end

app/controllers/backend/companions_controller.rb
class Backend::CompanionsController < ApplicationController
  layout 'backend'
  
  def index
    @doctors = Doctor.find(:all)
    @title = 'Manage companions'
  end
  
  def new
    @companion = Companion.new
    @doctors = Doctor.find(:all)
    @title = 'Add new companion'
  end
  
  def create
    @companion = Companion.new(params[:companion])    
    @title = 'Add new companion'
    
    if @companion.save
      flash[:notice] = 'A new companion has been added to the database.'
      render :show 
    else
      @doctors = Doctor.find(:all)
      render :new 
    end
  end
  
  def edit
    @companion = Companion.find(params[:id])
    @doctors = Doctor.find(:all)
    @title = 'Edit companions - ' << @companion.name
  end
  
  def update
    @companion = Companion.find(params[:id])
    @companion.attributes = params[:companion]
    @title = 'Update companions - ' << @companion.name
    
    if @companion.save
      flash[:notice] = 'The record has been updated. Users will now see it as it appears below.'
      render :show
    else
      @doctors = Doctor.find(:all)
      render :edit
    end
  end
  
  def show
    flash[:notice] = 'Below is the record as it appears to the public. See any problems? Corrections are a mouse click away.'
    @companion = Companion.find(params[:id])
  end
end

app/controllers/backend/contributors_controller.rb
class Backend::ContributorsController < ApplicationController
end

app/controllers/backend/doctors_controller.rb
class Backend::DoctorsController < ApplicationController
  layout 'backend'
  
  def index
    @doctors = Doctor.find(:all)
    @title = 'Manage Doctors'
  end
  
  def show
    @doctor = Doctor.find(params[:id])
    @title = 'Preview Doctor - ' << @doctor.label
  end
  
  def edit
    @doctor = Doctor.find(params[:id])
    @title = 'Edit - ' << @doctor.label
  end
  
  def update
    @doctor = Doctor.find(params[:id])
    @doctor.attributes = params[:doctor]
    @title = 'Preview Doctor - ' << @doctor.label

    if @doctor.save
      flash[:notice] = 'The database has been updated. Changes will appear immediately in the public interface.'
      redirect_to backend_doctor_path @doctor
    else
      render :edit
    end
  end

end

app/controllers/backend/entries_controller.rb
class Backend::EntriesController < ApplicationController
  layout 'backend'
  
  def new
    series = get_series params[:series_id]
    case series.category
      when 'Multimedia'
       @entry = VideoEntry.new
      when 'Print'
       @entry = PrintEntry.new
    end
    @entry.series = series
    @doctors = get_doctors(@entry.series.abbreviation)

    if ['vna', 'vma'].include? @entry.series.abbreviation
      @entry.publisher = Publisher.find_by_name('Virgin')
    elsif ['eda', 'pda', 'nsb', 'newseries', 'classic'].include? @entry.series.abbreviation
      @entry.publisher = Publisher.find_by_name('BBC')
    else
      @entry.publisher = nil
    end
    @title = 'Add new item - ' << @entry.series.name
  end

  def create
    series = get_series params[:series_id]
    case series.category
      when 'Multimedia'
       @entry = VideoEntry.new(params[:video_entry])
      when 'Print'
       @entry = PrintEntry.new(params[:print_entry])
    end
    @entry.companions = set_companions params[:companions]
    # Since get_doctors is already defined elsewhere we need to use a
    # localized method to retrieve the records
    @entry.doctors = set_doctors params[:doctors]
    @entry.contributors = set_contributors params[:contributors]

    @entry.publisher = set_publisher params[:publisher]
    @entry.series = series
    
    if @entry.save
      flash[:notice] = 'Entry has been added to the database. See below for a preview of how it will appear to the public.'  
      redirect_to backend_series_entry_path(:series_id => series.abbreviation, :id => @entry)
    else
      # For the form
      @doctors = get_doctors(@series.abbreviation)

      flash[:notice] = 'Something has gone wrong. Fix the errors and try again. If problems persist contact an administrator'
      render :new
    end
  end
  
  def edit
    @entry = Entry.find(params[:id])
    @doctors = get_doctors(@entry.series.abbreviation)
    
    @title = 'Edit item - ' << @entry.series.name
  end
  
  def update
    series = get_series params[:series_id]
    case series.category
      when 'Multimedia'
       logger.debug '<< Video entry >>'
       @entry = VideoEntry.find(params[:id])
       @entry.broadcast_status = params[:video_entry][:broadcast_status]
       logger.debug "<< #{@entry.broadcast_status} >>"
       case @entry.broadcast_status
         when 'unaired'
           @entry.broadcast_starting = nil
           @entry.broadcast_ending = nil
         when 'broadcast'
           @entry.broadcast_starting = params[:video_entry][:broadcast_starting]
           @entry.broadcast_ending = params[:video_entry][:broadcast_ending] 
       end
       param_name = 'video_entry'
      when 'Print'
       logger.debug '<< Print entry >>'
       @entry = PrintEntry.find(params[:id])
       param_name = 'print_entry'
    end
    
    @entry.companions = set_companions params[:companions]
    @entry.doctors = set_doctors params[:doctors]
    @entry.contributors = set_contributors params[:contributors]
    if ['otherbooks', 'spinoffs'].include?(@entry.series.abbreviation)
      @entry.publisher = set_publisher params[:publisher]
    end
    
    return_value = @entry.update_attributes params[param_name]
    logger.debug("Parameter name << #{param_name} >>")
    logger.debug(params[param_name])
    logger.debug("Return value << #{return_value} >>")
    
    if return_value
      flash[:notice] = 'Entry has been updated. Below is a preview of how it will appear to the public.'  
      redirect_to backend_series_entry_path(:series_id => series.abbreviation,
        :id => @entry)
    else
      @doctors = get_doctors(@series.abbreviation)
      render :edit
    end
  end
  
  def show
    @entry = Entry.find(params[:id])
  end
  
  protected
  def get_doctors(series)
    logger.debug "Series identifier is #{series}" 
    
    case series
      when 'vna'
        @doctors = Doctor.where(:id => [7, 8])
      when 'vma'
        @doctors = Doctor.where(:id => 1..6)
      when 'eda'
        @doctors = Doctor.find(8)
      when 'pda'
        @doctors = Doctor.where(:id => 1..7)
      when 'nsb'
        @doctors = Doctor.where(:id => 9..11)
      when 'classic'
        @doctors = Doctor.where(:id => 1..8)
      when 'newseries'
        @doctors = Doctor.where(:id => 9..11)
      else
        @doctors = Doctor.find(:all)  
    end
  end
  
  def set_companions(companions)
    return [] if companions.nil?
    
    companions.delete_if { |c| c.empty? }
    companion_list = Companion.where(:name => companions)
  end
  
  def set_contributors(contributors)
    return [] if contributors.nil?
    
    contributor_list = []
    logger.debug(contributors);
    contributors.delete_if { |c| c.empty? }
    
    contributors.each do |con|
      unless Contributor.exists?(:name => con)
        contributor_list.push Contributor.new(:name => con)      
      else
        contributor_list.push Contributor.find_by_name(con)
      end
    end
    return contributor_list
  end

  def set_doctors(doctors)
    return [] if doctors.nil?
    
    doctors.delete_if { |d| d.empty? }
    doctor_list = Doctor.where(:id => doctors)
  end
  
  def set_publisher(publisher)
    unless Publisher.exists?(:name => publisher)
      Publisher.new(:name => publisher)
    else
      Publisher.find_by_name(publisher)
    end
  end
  
  def get_series(series_id)
    if series_id =~ /^\d+$/
      @series = Series.find(series_id)
    else
      @series = Series.find_by_abbreviation(series_id)
    end
  end
end

app/controllers/backend/series_controller.rb
class Backend::SeriesController < ApplicationController
  layout 'backend'
  
  def index
    @series_hash = {}
    Series.find(:all).each do |s|
      @series_hash[s.abbreviation] = s
    end
    
    @title = 'Manage all series'
  end
  
  def show
    if params[:id] =~ /^\d+$/
      @series = Series.find(params[:id])
    else
      @series = Series.find_by_abbreviation(params[:id])
    end
    @title = 'Manage series - ' << @series.name
  end
  
  def edit
    if params[:id] =~ /^\d+$/
      @series = Series.find(params[:id])
    else
      @series = Series.find_by_abbreviation(params[:id])
    end
    @title = 'Edit series - ' << @series.name
  end
  
  def update
    logger.debug('Updating information for series')
    
    if params[:id] =~ /^\d+$/
      @series = Series.find(params[:id])
    else
      @series = Series.find_by_abbreviation(params[:id])
    end
    # Why do it this way? It ensure that the title and abbreviation can never
    # be overwritten by sending them as parameters
    @series.description = params[:series][:description]
    @series.series_started_on = params[:series][:series_started_on]
    @series.series_ended_on = params[:series][:series_ended_on]    
    
    if @series.save
      redirect_to backend_series_path(:id => @series.abbreviation), 
        :notice => 'The description has been updated'
    else
      render :edit
    end
  end
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
  layout 'backend'
  
  def index
    redirect_to :controller => 'backend/series', :action => 'index'
  end
end

app/controllers/companions_controller.rb
class CompanionsController < ApplicationController
end

app/helpers/backend/contributors_helper.rb
module Backend::ContributorsHelper
end

app/helpers/backend/entries_helper.rb
module Backend::EntriesHelper
end

app/helpers/backend/search_helper.rb
module Backend::SearchHelper
end

app/helpers/backend_helper.rb
module BackendHelper
end

app/views/backend/companions/_companion_form.html.erb
    <%= form_for([:backend, @companion],
    		    :html => {:id => "primary-form"}) do |f| %>
     <div class="label_and_fields">
       <div class="label">
         <%= f.label :uploaded_image, 'Image' %>
         <p class="tips">Supported image formats are JPEG and PNG</p>
       </div>
       <div class="fields">
         <% @companion.errors[:uploaded_image].each do |e| -%>
           <p class="errors"><%= e %></p>
         <% end -%>
         <% unless @companion.icon.nil? -%>
           <%= image_tag @companion.icon, :class => "preview", :alt => "Icon sized preview" %>
         <% else -%>
           <%= image_tag 'default-person.jpg', :class => 'preview' %>
         <% end -%>
         <%= f.file_field :uploaded_image %>
       </div>
     </div>

     <div class="label_and_fields">
       <div class="label">
         <%= f.label :name %>
       </div>
       <div class="fields">
         <% @companion.errors[:name].each do |e| -%>
           <p class="errors"><%= e %></p>
         <% end -%>
         <%= f.text_field :name, :size => 30, :placeholder => 'Complete name', :required => true %>
       </div>
     </div>

     <div class="label_and_fields">
       <div class="label">
         <%= f.label :played_by %>
       </div>
       <div class="fields">
         <% @companion.errors[:played_by].each do |e| -%>
           <p class="errors"><%= e %></p>
         <% end -%>
         <%= f.text_field :played_by, :size => 60, :placeholder => 'Actor / actress', :required => true %>
       </div>
     </div>
     
      <div class="label_and_fields">
        <div class="label">
          <%= f.label :doctors, 'Travels with' %>
        </div>
      <div class="fields">
        <div class="columns">
          <% @doctors.each do |doctor| -%>
            <label><input type="checkbox" name="companion[doctor_ids][]" id="companion_doctors_<%= doctor.id %>" value="<%= doctor.id %>"<%- if params[:doctor].to_i == doctor.id or @companion.doctor_ids.include?(doctor.id) -%> checked<% end -%>><%= doctor.label %></label>
          <% end -%>
        </div>
      </div>
     </div>

      <div class="label_and_fields">
        <div class="label">
          <%= f.label :description, 'Summary' %>
          <p class="tips">A brief biography</p>
        </div>
      <div class="fields">
        <%= f.text_area :description, :size => "60x20" %>
       </div>
     </div>

       <div class="fields">
         <%= submit_tag "Preview changes" %>
         <span class="cancel_form button"><%= link_to 'Return to list', [:backend, :companions] %></span>
       </div>
    <% end %>

    <% content_for :scripts do %>
    <script type="text/javascript">
      $(function() {
        $('input[type="submit"]').replaceWith('<span class="submit_form button"><a href="#">Save changes</a></span>');
        
        $('.submit_form a').click(
          function() { $('form').submit(); }
        );        
      });
    </script>
    <% end -%>

app/views/backend/companions/_companion_list.html.erb
        <div class="columns">
          <ul>
        <% unless 0 == companions.length -%>
            <% companions.each do |c| -%>
              <li><%= link_to c.name, [:backend, c] %></li>
            <% end -%>
        <% else -%>
            <li class="emphasis">No companions</li>
        <% end -%>
            <li class="button add_item"><%= link_to '+', 
              :controller => :companions,
              :action => 'new',
              :doctor => doctor_id
              %></li>
          </ul>
        </div>

app/views/backend/companions/edit.html.erb
    <section class="page_context">
      <nav class="breadcrumbs">
          <%= link_to 'administration', :backend %>
          <%= link_to 'Companions', [:backend, :companions] %>
          Edit <%= @companion.name %>
        </ul>
      </nav>

      <h1>Edit <%= @companion.name %></h1>
    </section>
    
    <%= render 'companion_form' %>

app/views/backend/companions/index.html.erb
    <section class="page_context">
      <nav class="breadcrumbs">
          <%= link_to 'administration', :backend %>
          Companions
        </ul>
      </nav>

      <h1>Companions</h1>
      <article class="summary">
        <p>What would the Doctor be without his travel companions? From Susan, Ian, and Barbara through Sarah Jane and Jo Grant all the way down to Rose Tyler and Donna Noble each has brought their own dynamic to their relationship with the nomadic Time Lord.</p>
      </article>
    </section>

    <% for doctor in @doctors do -%>
    <section class="cluster">
        <figure>
          <%= image_tag doctor.icon, 
            :alt => "Companions of the #{doctor.label}",
            :title => "#{doctor.label}" %>
          <figcaption><%= doctor.label %></figcaption>
        </figure>

        <div class="companion_list"><%= render :partial => 'companion_list', :locals => {:companions => doctor.companions, :doctor_id => doctor.id } %></div>
    </section>
    <% end -%>
    
    <section class="cluster">
        <figure>
          <%= image_tag 'companions-other.png', 
            :alt => "Additional companions",
            :title => "Additional companions" %>
          <figcaption>Other companions</figcaption>
        </figure>
        <div class="companion_list">
          <div class="columns">
            <ul>
              <li class="empty">No companions</li>
              <li class="button add_item"><%= link_to '+', 
              :controller => :companions,
              :action => 'new' %></li>
            </ul>
          </div>
        </div>
    </section>

app/views/backend/companions/new.html.erb
    <section class="page_context">
      <nav class="breadcrumbs">
          <%= link_to 'administration', :backend %>
          <%= link_to 'Companions', [:backend, :companions] %>
          Add new companion
        </ul>
      </nav>

      <h1>Add new companion</h1>
    </section>
    
    <%= render 'companion_form' %>

app/views/backend/companions/show.html.erb
    <section class="page_context">
      <nav class="breadcrumbs">
          <%= link_to 'administration', :backend %>
          <%= link_to 'companions', [:backend, :companions] %>
          <%= @companion.name %>
        </ul>
      </nav>
    </section>

    <% if flash[:notice] -%>
    <section class="preview_controls">
      <p><%= flash[:notice] %></p>
    </section>
    <% end -%>
    
    <article class="summary">
      <%= render :partial => "shared/companion_summary" %>
      
      <nav>
        <%= link_to 'i', edit_backend_companion_path(@companion), :class => 'edit_item button' %>
        <%= link_to 'x', backend_companions_path, :class => "delete_item button" %>
      </nav>
    </section>

    </article>