config/routes.rb
Sidrat::Application.routes.draw do

  namespace :backend do
    resources :doctors, :except => [:new, :create, :destroy]
    resources :companions, :except => [:destroy]
    resources :series, :except => [:new, :create, :destroy] do
      resources :entries, :except => [:index, :destroy]
    end
  end
  
  match '/search/companion' => 'searches#companion'
  match '/search/contributor' => 'searches#contributor'
  match '/search/publisher' => 'searches#publisher'
  
  match '/backend/index' => 'backend#index'
  match '/backend' => 'backend#index'
  
  
  match '/doctors' => 'doctors#index'
  

  root :to => 'sidrat#index'

end

app/controllers/backend/companions_controller.rb
class Backend::CompanionsController < ApplicationController
  layout 'backend'
  
  def index
    @doctors = Doctor.find(:all)
    @title = 'Manage companions'
  end
  
  def new
    @companion = Companion.new
    @doctors = Doctor.find(:all)
    @title = 'Add new companion'
  end
  
  def create
    @companion = Companion.new(params[:companion])    
    @title = 'Add new companion'
    
    if @companion.save
      flash[:notice] = 'A new companion has been added to the database.'
      render :show 
    else
      @doctors = Doctor.find(:all)
      render :new 
    end
  end
  
  def edit
    @companion = Companion.find(params[:id])
    @doctors = Doctor.find(:all)
    @title = 'Edit companions - ' << @companion.name
  end
  
  def update
    @companion = Companion.find(params[:id])
    @companion.attributes = params[:companion]
    @title = 'Update companions - ' << @companion.name
    
    if @companion.save
      flash[:notice] = 'The record has been updated. Users will now see it as it appears below.'
      render :show
    else
      @doctors = Doctor.find(:all)
      render :edit
    end
  end
  
  def show
    flash[:notice] = 'Below is the record as it appears to the public. See any problems? Corrections are a mouse click away.'
    @companion = Companion.find(params[:id])
  end
end

app/controllers/backend/contributors_controller.rb
class Backend::ContributorsController < ApplicationController
end

app/controllers/backend/doctors_controller.rb
class Backend::DoctorsController < ApplicationController
  layout 'backend'
  
  def index
    @doctors = Doctor.find(:all)
    @title = 'Manage Doctors'
  end
  
  def show
    @doctor = Doctor.find(params[:id])
    @title = 'Preview Doctor - ' << @doctor.label
  end
  
  def edit
    @doctor = Doctor.find(params[:id])
    @title = 'Edit - ' << @doctor.label
  end
  
  def update
    @doctor = Doctor.find(params[:id])
    @doctor.attributes = params[:doctor]
    @title = 'Preview Doctor - ' << @doctor.label

    if @doctor.save
      flash[:notice] = 'The database has been updated. Changes will appear immediately in the public interface.'
      redirect_to backend_doctor_path @doctor
    else
      render :edit
    end
  end

end

app/controllers/backend/entries_controller.rb
class Backend::EntriesController < ApplicationController
  layout 'backend'
  
  def new
    series = get_series params[:series_id]
    case series.category
      when 'Multimedia'
       @entry = VideoEntry.new
      when 'Print'
       @entry = PrintEntry.new
    end
    @entry.series = series
    @doctors = get_doctors(@entry.series.abbreviation)

    if ['vna', 'vma'].include? @entry.series.abbreviation
      @entry.publisher = Publisher.find_by_name('Virgin')
    elsif ['eda', 'pda', 'nsb', 'newseries', 'classic'].include? @entry.series.abbreviation
      @entry.publisher = Publisher.find_by_name('BBC')
    else
      @entry.publisher = nil
    end
    @title = 'Add new item - ' << @entry.series.name
  end

  def create
    series = get_series params[:series_id]
    case series.category
      when 'Multimedia'
       @entry = VideoEntry.new(params[:video_entry])
      when 'Print'
       @entry = PrintEntry.new(params[:print_entry])
    end
    @entry.companions = set_companions params[:companions]
    # Since get_doctors is already defined elsewhere we need to use a
    # localized method to retrieve the records
    @entry.doctors = set_doctors params[:doctors]
    @entry.contributors = set_contributors params[:contributors]

    @entry.publisher = set_publisher params[:publisher]
    @entry.series = series
    
    if @entry.save
      flash[:notice] = 'Entry has been added to the database. See below for a preview of how it will appear to the public.'  
      redirect_to backend_series_entry_path(:series_id => series.abbreviation, :id => @entry)
    else
      # For the form
      @doctors = get_doctors(@series.abbreviation)

      flash[:notice] = 'Something has gone wrong. Fix the errors and try again. If problems persist contact an administrator'
      render :new
    end
  end
  
  def edit
    @entry = Entry.find(params[:id])
    @doctors = get_doctors(@entry.series.abbreviation)
    
    @title = 'Edit item - ' << @entry.series.name
  end
  
  def update
    series = get_series params[:series_id]
    case series.category
      when 'Multimedia'
       logger.debug '<< Video entry >>'
       @entry = VideoEntry.find(params[:id])
       @entry.broadcast_status = params[:video_entry][:broadcast_status]
       logger.debug "<< #{@entry.broadcast_status} >>"
       case @entry.broadcast_status
         when 'unaired'
           @entry.broadcast_starting = nil
           @entry.broadcast_ending = nil
         when 'broadcast'
           @entry.broadcast_starting = params[:video_entry][:broadcast_starting]
           @entry.broadcast_ending = params[:video_entry][:broadcast_ending] 
       end
       param_name = 'video_entry'
      when 'Print'
       logger.debug '<< Print entry >>'
       @entry = PrintEntry.find(params[:id])
       param_name = 'print_entry'
    end
    
    @entry.companions = set_companions params[:companions]
    @entry.doctors = set_doctors params[:doctors]
    @entry.contributors = set_contributors params[:contributors]
    if ['otherbooks', 'spinoffs'].include?(@entry.series.abbreviation)
      @entry.publisher = set_publisher params[:publisher]
    end
    
    return_value = @entry.update_attributes params[param_name]
    logger.debug("Parameter name << #{param_name} >>")
    logger.debug(params[param_name])
    logger.debug("Return value << #{return_value} >>")
    
    if return_value
      flash[:notice] = 'Entry has been updated. Below is a preview of how it will appear to the public.'  
      redirect_to backend_series_entry_path(:series_id => series.abbreviation,
        :id => @entry)
    else
      @doctors = get_doctors(@series.abbreviation)
      render :edit
    end
  end
  
  def show
    @entry = Entry.find(params[:id])
  end
  
  protected
  def get_doctors(series)
    logger.debug "Series identifier is #{series}" 
    
    case series
      when 'vna'
        @doctors = Doctor.where(:id => [7, 8])
      when 'vma'
        @doctors = Doctor.where(:id => 1..6)
      when 'eda'
        @doctors = Doctor.find(8)
      when 'pda'
        @doctors = Doctor.where(:id => 1..7)
      when 'nsb'
        @doctors = Doctor.where(:id => 9..11)
      when 'classic'
        @doctors = Doctor.where(:id => 1..8)
      when 'newseries'
        @doctors = Doctor.where(:id => 9..11)
      else
        @doctors = Doctor.find(:all)  
    end
  end
  
  def set_companions(companions)
    return [] if companions.nil?
    
    companions.delete_if { |c| c.empty? }
    companion_list = Companion.where(:name => companions)
  end
  
  def set_contributors(contributors)
    return [] if contributors.nil?
    
    contributor_list = []
    logger.debug(contributors);
    contributors.delete_if { |c| c.empty? }
    
    contributors.each do |con|
      unless Contributor.exists?(:name => con)
        contributor_list.push Contributor.new(:name => con)      
      else
        contributor_list.push Contributor.find_by_name(con)
      end
    end
    return contributor_list
  end

  def set_doctors(doctors)
    return [] if doctors.nil?
    
    doctors.delete_if { |d| d.empty? }
    doctor_list = Doctor.where(:id => doctors)
  end
  
  def set_publisher(publisher)
    unless Publisher.exists?(:name => publisher)
      Publisher.new(:name => publisher)
    else
      Publisher.find_by_name(publisher)
    end
  end
  
  def get_series(series_id)
    if series_id =~ /^\d+$/
      @series = Series.find(series_id)
    else
      @series = Series.find_by_abbreviation(series_id)
    end
  end
end

app/controllers/backend/series_controller.rb
class Backend::SeriesController < ApplicationController
  layout 'backend'
  
  def index
    @series_hash = {}
    Series.find(:all).each do |s|
      @series_hash[s.abbreviation] = s
    end
    
    @title = 'Manage all series'
  end
  
  def show
    if params[:id] =~ /^\d+$/
      @series = Series.find(params[:id])
    else
      @series = Series.find_by_abbreviation(params[:id])
    end
    @title = 'Manage series - ' << @series.name
  end
  
  def edit
    if params[:id] =~ /^\d+$/
      @series = Series.find(params[:id])
    else
      @series = Series.find_by_abbreviation(params[:id])
    end
    @title = 'Edit series - ' << @series.name
  end
  
  def update
    logger.debug('Updating information for series')
    
    if params[:id] =~ /^\d+$/
      @series = Series.find(params[:id])
    else
      @series = Series.find_by_abbreviation(params[:id])
    end
    # Why do it this way? It ensure that the title and abbreviation can never
    # be overwritten by sending them as parameters
    @series.description = params[:series][:description]
    @series.series_started_on = params[:series][:series_started_on]
    @series.series_ended_on = params[:series][:series_ended_on]    
    
    if @series.save
      redirect_to backend_series_path(:id => @series.abbreviation), 
        :notice => 'The description has been updated'
    else
      render :edit
    end
  end
end

app/controllers/backend_controller.rb
class BackendController < ApplicationController
  layout 'backend'
  
  def index
    redirect_to :controller => 'backend/series', :action => 'index'
  end
end

app/helpers/backend/contributors_helper.rb
module Backend::ContributorsHelper
end

app/helpers/backend/entries_helper.rb
module Backend::EntriesHelper
end

app/helpers/backend/search_helper.rb
module Backend::SearchHelper
end

app/helpers/backend_helper.rb
module BackendHelper
end

app/views/backend/series/_default_list.html.erb
    <section class="entries">
      <table>
        <colgroup span="1" class="title" />
        <colgroup span="1" class="author" />
        <colgroup span="1" class="release_date" />
        <colgroup span="1" class="featuring" />
        <colgroup span="1" class="publisher" />
        
        <thead>
          <tr>
            <td class="sortable">Title</td>
            <td class="sortable">Author</td>
            <td class="sortable">Release Date</td>
            <td>Featuring</td>
            <td class="sortable">Publisher</td>
          </tr>
        </thead>
        
        <tbody>
        <% if 0 == entries.length -%>
          <tr>
            <td colspan="5">
              <p class="emphasis">No entries currently exist for this series.</p>
            </td>
          </tr>
        <% else -%>
          <% entries.each do |e| -%>
            <tr>
              <td><%= link_to e.title, backend_series_entry_path(:series_id => @series.abbreviation, :id => e) %></td>
              <td><%= written_by e.contributors.to_a %></td>
              <td><%= e.released_on.strftime("%B %Y") %></td>
              <td><%= featuring e.doctors.to_a, e.companions.to_a %></td>
              <td><%= e.publisher.name %></td>
            </tr>
          <% end -%>
        <% end -%>
        </tbody>
      </table>
    </section>
        

app/views/backend/series/_multiple_doctor_list.html.erb
    <section class="entries">
      <table>
        <colgroup span="1" class="title" />
        <colgroup span="1" class="author" />
        <colgroup span="1" class="release_date" />
        <colgroup span="1" class="featuring" />
        <colgroup span="1" class="publisher" />
        
        <thead>
          <tr>
            <td class="sortable">Title</td>
            <td class="sortable">Author</td>
            <td class="sortable">Release Date</td>
            <td>Featuring</td>
            <td class="sortable">Publisher</td>
          </tr>
        </thead>
        
        <tbody>
        <% if 0 == entries.length -%>
          <tr>
            <td colspan="5">
              <p class="emphasis">No entries currently exist for this series.</p>
            </td>
          </tr>
        <% else -%>
          <% entries.each do |e| -%>
            <tr>
              <td><%= link_to e.title, backend_series_entry_path(:series_id => @series.abbreviation, :id => e) %></td>
              <td><%= written_by e.contributors.to_a %></td>
              <td><%= e.released_on.strftime("%B %Y") %></td>
              <td><%= featuring e.doctors.to_a, e.companions.to_a %></td>
              <td><%= e.publisher.name %></td>
            </tr>
          <% end -%>
        <% end -%>
        </tbody>
      </table>
    </section>
        

app/views/backend/series/_series_figure.html.erb
<figure>
    <%= link_to image_tag (series.image, 
        :title => series.name),
        backend_series_path(:id => series.abbreviation) %>
  <figcaption><%= series.name %></figcaption>
</figure>

app/views/backend/series/_single_doctor_list.html.erb
    <section class="entries">
      <table>
        <colgroup span="1" class="title" />
        <colgroup span="1" class="author" />
        <colgroup span="1" class="release_date" />
        <colgroup span="1" class="featuring" />
        <colgroup span="1" class="publisher" />
        
        <thead>
          <tr>
            <td class="sortable">Title</td>
            <td class="sortable">Author</td>
            <td class="sortable">Release Date</td>
            <td>Featuring</td>
            <td class="sortable">Publisher</td>
          </tr>
        </thead>
        
        <tbody>
        <% if 0 == entries.length -%>
          <tr>
            <td colspan="5">
              <p class="emphasis">No entries currently exist for this series.</p>
            </td>
          </tr>
        <% else -%>
          <% entries.each do |e| -%>
            <tr>
              <td><%= link_to e.title, backend_series_entry_path(:series_id => @series.abbreviation, :id => e) %></td>
              <td><%= written_by e.contributors.to_a %></td>
              <td><%= e.released_on.strftime("%B %Y") %></td>
              <td><%= featuring e.doctors.to_a, e.companions.to_a %></td>
              <td><%= e.publisher.name %></td>
            </tr>
          <% end -%>
        <% end -%>
        </tbody>
      </table>
    </section>
        

app/views/backend/series/_spinoffs_list.html.erb
    <section class="entries">
      <table>
        <colgroup span="1" class="title" />
        <colgroup span="1" class="author" />
        <colgroup span="1" class="release_date" />
        <colgroup span="1" class="format" />
        <colgroup span="1" class="publisher" />
        <colgroup span="1" class="featuring" />
        
        <thead>
          <tr>
            <td class="sortable">Title</td>
            <td class="sortable">Author</td>
            <td class="sortable">Release Date</td>
            <td class="sortable">Publisher</td>
            <td class="sortable">Format</td>
            <td>Featuring</td>
          </tr>
        </thead>
        
        <tbody>
        <% if 0 == entries.length -%>
          <tr>
            <td colspan="5">
              <p class="emphasis">No entries currently exist for this series.</p>
            </td>
          </tr>
        <% else -%>
          <% entries.each do |e| -%>
            <tr>
              <td><%= link_to e.title, backend_series_entry_path(:series_id => @series.abbreviation, :id => e) %></td>
              <td><%= written_by e.contributors.to_a %></td>
              <td><%= e.released_on.strftime("%B %Y") %></td>
              <td><%= e.publisher.name %></td>
              <td><%= e.format %></td>
              <td><%= featuring e.doctors, e.companions %></td>
            </tr>
          <% end -%>
        <% end -%>
        </tbody>
      </table>
    </section>
        

app/views/backend/series/_video_list.html.erb
    <section class="entries">
      <table>
        <colgroup span="1" class="title" />
        <colgroup span="1" class="author" />
        <colgroup span="1" class="episode" />
        <colgroup span="1" class="release_date" />
        <colgroup span="1" class="status" />
        <colgroup span="1" class="featuring" />
        <colgroup span="1" />
        
        <thead>
          <tr>
            <td class="sortable">Title</td>
            <td class="sortable">Author</td>
            <td class="sortable">Serial</td>
            <td class="sortable">Release Date</td>
            <td>Status</td>
            <td>Featuring</td>
            <td>&nbsp;</td>
          </tr>
        </thead>
        
        <tbody>
        <% if 0 == entries.length -%>
          <tr>
            <td colspan="5">
              <p class="emphasis">No entries currently exist for this series.</p>
            </td>
          </tr>
        <% else -%>
          <% entries.each do |e| -%>
            <tr>
              <td><%= link_to e.title, backend_series_entry_path(:series_id => @series.abbreviation, :id => e) %></td>
              <td><%= written_by e.contributors.to_a %></td>
              <td><% unless e.episode.nil? -%><%= e.episode %><% else -%>N/A<% end -%></td>
              <td><%= e.released_on.strftime("%B %Y") %> (<%= e.format %>)</td>
              <td><% unless e.status.nil? -%><%= e.status %><% else -%>Unknown<% end -%>
              <td><%= featuring e.doctors.to_a, e.companions.to_a %></td>
              <td><%= link_to 'Edit entry', edit_backend_series_entry_path(:series_id => e.series.abbreviation, :id => e) %></td>
            </tr>
          <% end -%>
        <% end -%>
        </tbody>
      </table>
    </section>
        

app/views/backend/series/edit.html.erb
    <section class="page_context">
      <nav class="breadcrumbs">
          <%= link_to 'administration', :backend %>
          <%= link_to 'series', backend_series_index_path %>
          Edit series details (<%= @series.name %>)
        </ul>
      </nav>

      <h1>Edit series details</h1>
    </section>

    <%= form_for([:backend, @series],
                :url => backend_series_path(:id => @series.abbreviation),
    		    :html => {:id => "primary-form"}) do |f| %>
     <div class="label_and_fields">
       <div class="label">
         <%= f.label :name, 'Name' %>
       </div>
       <div class="fields">
         <p class="static"><%= @series.name %></p>
       </div>
     </div>

     <div class="label_and_fields">
       <div class="label">
         <%= f.label :series_started_on, 'Series spans' %>
       </div>
       <div class="fields">
         <% @series.errors[:series_started_on].each do |e| -%>
           <p class="errors"><%= e %></p>
         <% end -%>
         <% @series.errors[:series_ended_on].each do |e| -%>
           <p class="errors"><%= e %></p>
         <% end -%>
         <%= f.select :series_started_on, (1963..Date.today.year) %> to
         <%= f.select :series_ended_on, (1964..Date.today.year) %>          
       </div>
     </div>

     <div class="label_and_fields">
       <div class="label">
         <%= f.label :uploaded_image, 'Image' %>
         <p class="tips">Supported image formats are JPEG and PNG</p>
       </div>
       <div class="fields">
         <% @series.errors[:uploaded_image].each do |e| -%>
           <p class="errors"><%= e %></p>
         <% end -%>
         <% unless @series.image.nil? -%>
           <%= image_tag @series.image, :class => "preview", :alt => "Icon sized preview" %>
         <% else -%>
           <%= image_tag 'default-person.jpg', :class => 'preview' %>
         <% end -%>
         <%= f.file_field :uploaded_image %>
       </div>
     </div>

      <div class="label_and_fields">
        <div class="label">
          <%= f.label :description, 'Summary' %>
          <p class="tips">A brief summary</p>
        </div>
      <div class="fields">
        <%= f.text_area :description, :size => "60x20" %>
       </div>
     </div>

       <div class="fields">
         <%= submit_tag "Preview changes" %>
         <span class="cancel_form button"><%= link_to 'Return to list',   
           [:backend, :series], 
           :id => @series.abbreviation %></span>
       </div>
    <% end %>

    <% content_for :scripts do %>
    <script type="text/javascript">
      $(function() {
        $('input[type="submit"]').replaceWith('<span class="submit_form button"><a href="#">Save changes</a></span>');
        
        $('.submit_form a').click(
          function() { $('form').submit(); }
        );        
      });
    </script>
    <% end -%>

app/views/backend/series/index.html.erb
    <section class="page_context">
      <nav class="breadcrumbs">
          <%= link_to 'administration', :backend %>
          series
        </ul>
      </nav>

      <h1>Database administration</h1>
      <p>Need to add or update a record for an upcoming release? Select a category from the list below to get started.</p>
      <hr />
    </section>

    <section class="cluster">
    <h2>Books and print</h2>  
      <section class="subgroup">
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['vna'] } %>     
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['vma'] } %>     
      </section>
      
      <section class="subgroup">
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['eda'] } %>     
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['pda'] } %>     
      </section>
      
      <section class="subgroup">
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['nsb'] } %>     
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['otherbooks'] } %>     
      </section>
    </section>
    
    <section class="cluster">
    <h2>Video and audio</h2>
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['classic'] } %>     
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['newseries'] } %>     
      <%= render :partial => 'series_figure', 
        :locals => { :series => @series_hash['spinoffs'] } %>     
      </figure>
    </section>

app/views/backend/series/show.html.erb
    <section class="page_context">
      <nav class="breadcrumbs">
          <%= link_to 'administration', :backend %>
          <%= link_to 'series', backend_series_index_path %>
          <%= @series.name %>
        </ul>
      </nav>

      <article class="summary">
        <%= render :partial => 'shared/series_summary', 
          :local => { :series => @series } %>
        <nav>
          <span class="edit_item button"><%= link_to 'i',
            edit_backend_series_path(:id => @series.abbreviation) %></span>
          <span class="add_item button"><%= link_to '+',
            new_backend_series_entry_path(:series_id => @series.abbreviation) %></span>
        </nav>
      </article>
    </section>

    <% if ['vna', 'eda'].include? @series.abbreviation
      partial = 'single_doctor_list'
    elsif ['vna', 'pda', 'nsb'].include? @series.abbreviation
      partial = 'multiple_doctor_list'
    elsif ['classic', 'newseries'].include? @series.abbreviation
      partial = 'video_list'
    elsif ['spinoffs', 'otherbooks'].include? @series.abbreviation
      partial = 'spinoffs_list'
    else 
      partial = 'default_list'
    end -%>
    <% unless 'classic' == @series.abbreviation -%>
      <%= render :partial => partial, :locals => { :entries => @series.entries } %>
    <% else 
      @series.entries.group_by(&:season).each do |season, entries| -%>      
        <h2><% if 0 == season -%>Specials<% else -%>Season <%= season %><% end -%></h2>
        <%= render :partial => partial, :locals => { :entries => entries } %>
      <% end 
     end -%>