config/routes.rb
Sidrat::Application.routes.draw do

  namespace :backend do
    resources :doctors, :except => [:new, :create, :destroy]
    resources :companions, :except => [:destroy]
    resources :series, :except => [:new, :create, :destroy] do
      resources :entries, :except => [:index, :destroy]
    end
  end
  
  match '/search/companion' => 'searches#companion'
  match '/search/contributor' => 'searches#contributor'
  match '/search/publisher' => 'searches#publisher'
  
  match '/backend/index' => 'backend#index'
  match '/backend' => 'backend#index'
  
  
  match '/doctors' => 'doctors#index'
  

  root :to => 'sidrat#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SIDRAT - Home</title>

    <%= stylesheet_link_tag 'base-styles', :media => 'all' %>
    <%= stylesheet_link_tag 'print-styles', :media => 'print' %>
  </head>
  
  <body>
    <header>
      <span class="logo"><a href="index"><%= image_tag "sidrat-logo.png", :title => "SIDRAT - Special Inventory of DVDs, Recordings, and Texts" %></a></span>
      
      <div class="banner">
        <h1>SIDRAT</h1>
        <p class="tagline">Special Inventory of DVDs, Recordings, and Texts</p>
      </div>
    </header>
    
    <%= yield %>
    
    <footer>
      <nav>
        <a href="index.html">home</a>
        <a href="media.html">by media</a>
        <a href="doctor.html">by doctor</a>
        <a href="companion.html">by companion</a>
        <a href="search.html">search</a>
      </nav>
      
      <p class="copyright">
        &copy; 2011 by Nathan Rogers<br />
      </p>
    </footer>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctor Who Inventory Manager <% if not @title.nil? -%>- <%= @title %><% end -%></title>
    
    <%= stylesheet_link_tag 'base-styles', :media => 'all' %>
    <%= stylesheet_link_tag 'admin-styles', :media => 'all' %>
    <%= stylesheet_link_tag 'print-styles', :media => 'print' %>
    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/themes/redmond/jquery-ui.css" %>    
    
    <%= javascript_include_tag 'application' %>
  </head>
  
  <body>
    <header>
      <span class="logo"><%= link_to image_tag("sidrat-logo.png", 
        :title => "SIDRAT - Special Inventory of DVDs, Recordings, and Texts"),
        :backend %></span>
      
      <div class="banner">
        <h1>SIDRAT</h1>
        <p class="tagline">Special Inventory of DVDs, Recordings, and Texts</p>
      </div>
    </header>
    
    <nav class="global primary">
        <%= link_to 'series', backend_series_index_path %>
        <%= link_to 'doctors', backend_doctors_path %>
        <%= link_to 'companions', backend_companions_path %>
        <a href="/backend/contributors">contributors</a>
        <a href="/backend/search">search</a>
    </nav>
    
    <%= yield %>
    
    <footer>
      <nav>
        <%= link_to 'series', backend_series_index_path %>
        <%= link_to 'doctors', [:backend, :doctors] %>
        <%= link_to 'companions', [:backend, :companions] %>
        <a href="/backend/contributors">contributors</a>
        <a href="/backend/search">search</a>
      </nav>
      
      <p class="copyright">
        &copy; 2011 by Nathan Rogers<br />
      </p>
    </footer>
    
    <%= yield :scripts %>
  </body>
</html>